### ISSUE TITLE
Problem with uploading!

### ISSUE THREAD

**Issue by krak3n77** [phikshun/uDuck#1]
user$ python uduck_upload.py youtube-blaster.txt
CAN'T PROCESS... REM Author: Cody Theodore
CAN'T PROCESS... REM Title: OSX Youtube Blast
CAN'T PROCESS... REM This payload will open terminal, crank up the Macs volume all the way, then open a youtube video of
CAN'T PROCESS... REM your choice by replacing the link.
[+] Successfully compiled duckyscript
[+] Reading firmware image
[+] Patching firmware
[+] Successfully patched firmware

[+] Please plug in your uDuck device...
Press Ctrl-C to terminate the program...

Traceback (most recent call last):
  File "uduck_upload.py", line 414, in <module>
    mn.connect()
  File "uduck_upload.py", line 237, in connect
    self.flash_size, self.page_size, buf3, self.signature = struct.unpack('>HBBH', ret)
struct.error: unpack requires a string argument of length 6
user$ 

Help please

**Comment by gloglas** [comment]
Help please too
